# Generated by Django 5.2.8 on 2025-11-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
