# Generated by Django 5.2.8 on 2025-11-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_image_alter_galleryimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibitorregistration',
            old_name='contact_person',
            new_name='contact_person_name',
        ),
        migrations.RenameField(
            model_name='exhibitorregistration',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='exhibitorregistration',
            old_name='product',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='visitorregistration',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='visitorregistration',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='visitorregistration',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
