# Generated by Django 5.2.8 on 2025-11-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contact_person_exhibitorregistration_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
